### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by loveogithub** [bsmali4/xssfork#10]
Traceback (most recent call last):
  File "/root/github/xssfork/common/../taskschedule/task_thread.py", line 176, in run
    self.check_xss(payload)
  File "/root/github/xssfork/common/../taskschedule/task_thread.py", line 142, in check_xss
    child_process, payload = self.sub_process_open(payload)
  File "/root/github/xssfork/common/../taskschedule/task_thread.py", line 122, in sub_process_open
    request_command, url_payload, destination_command = self.get_cmd(payload)
  File "/root/github/xssfork/common/../taskschedule/task_thread.py", line 100, in get_cmd
    url_payload = self.replace_url_to_payload(payload)
  File "/root/github/xssfork/common/../taskschedule/task_thread.py", line 89, in replace_url_to_payload
    url_payload = re.subn(r'bsmali4_(?:int|mix|other|str|float)', payload, url_payload)[0]
  File "/usr/lib/python2.7/re.py", line 166, in subn
    return _compile(pattern, flags).subn(repl, string, count)
  File "/usr/lib/python2.7/re.py", line 286, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python2.7/re.py", line 266, in _compile_repl
    p = _cache_repl.get(key)
TypeError: unhashable type: 'dict'

当扫描的是卡在payload测试那儿，看data/exception.log出现的是这个错误。

**Comment by bsmali4** [comment]
关于卡住的问题，我这边目前还没有出现，我找个时间单独测下。
