### ISSUE TITLE
ImportError: No module named colorlog

### ISSUE THREAD

**Issue by clayclayclay** [bsmali4/xssfork#17]
环境：MacOs, python 2.7.14
输入：python2.7 xssfork.py  -u http://xssfork.codersec.net/xssdemo.php?id=23
`
Traceback (most recent call last):
  File "xssfork.py", line 87, in <module>
    help()
  File "xssfork.py", line 63, in help
    task_schedule.main()
  File "/Users/lvxiaoqian/tools/xss/xssfork/common/../taskschedule/task_schedule.py", line 54, in main
    self.check_complete_packet_is_alive()
  File "/Users/lvxiaoqian/tools/xss/xssfork/common/../taskschedule/task_schedule.py", line 88, in check_complete_packet_is_alive
    self.check_complete_url_is_alive()
  File "/Users/lvxiaoqian/tools/xss/xssfork/common/../taskschedule/task_schedule.py", line 92, in check_complete_url_is_alive
    logger = log.get_logger()
  File "/Users/lvxiaoqian/tools/xss/xssfork/common/log.py", line 27, in get_logger
    init_config()
  File "/Users/lvxiaoqian/tools/xss/xssfork/common/log.py", line 55, in init_config
    stream_handler = get_stream_handler()
  File "/Users/lvxiaoqian/tools/xss/xssfork/common/log.py", line 44, in get_stream_handler
    from colorlog import ColoredFormatter
ImportError: No module named colorlog
`
请问这个是怎么回事呢？

**Comment by bsmali4** [comment]
pip install colorlog
