### ISSUE TITLE
Windows无法使用吗

### ISSUE THREAD

**Issue by LangziFun** [bsmali4/xssfork#21]

**Comment by bsmali4** [comment]
可以提供详细的报错信息吗？之前在win10上测试可用

**Comment by LangziFun** [comment]
C:\Users\Administrator\Desktop\xssfork>python xssfork.py -u "http://127.0.0.1/xss/level2.php?keyword=ad&submit=%E6%90%9C%E7%B4%A2"

               __           _
              / _|         | |
__  _____ ___| |_ ___  _ __| | __
\ \/ / __/ __|  _/ _ \| '__| |/ /   version: 1.0.2#dev
 >  <\__ \__ \ || (_) | |  |   <    author: b5mali4
/_/\_\___/___/_| \___/|_|  |_|\_\  http://xssfork.secbug.net


[16:16:15] [DEBUG] checking if url is available
[16:16:15] [INFO] url connection success
[16:16:15] [DEBUG] checking if destination is available
[16:16:15] [INFO] destination connection success
[16:16:15] [DEBUG] checking if has_params
[16:16:15] [INFO] there is params, xssfork will work
[16:16:15] [INFO] loading default paloads
[16:16:15] [INFO] loading default paloads success
[16:16:15] [INFO] 1527 payloads loaded
Traceback (most recent call last):...
  File "xssfork.py", line 87, in <module>
    help()
  File "xssfork.py", line 63, in help
    task_schedule.main()
  File "C:\Users\Administrator\Desktop\xssfork\common/../taskschedule\task_schedule.py", line 65, in main
    XssVulnerability.notif_all(self.kill_threads)
  File "C:\Users\Administrator\Desktop\xssfork\common/../taskschedule\xss_vulnerability.py", line 21, in notif_all
    call_back()
  File "C:\Users\Administrator\Desktop\xssfork\common/../taskschedule\task_schedule.py", line 118, in kill_threads
    fuzz_thread.kill_sub_process()
  File "C:\Users\Administrator\Desktop\xssfork\common/../taskschedule\task_thread.py", line 160, in kill_sub_process
    os.killpg(temp_child_process.pid, signal.SIGTERM)
AttributeError: 'module' object has no attribute 'killpg'

C:\Users\Administrator\Desktop\xssfork>

机器是Windows10 ，看报错应该是Windows下os模块不提供killpg这个api，killpg好像只能在linux下支持

**Comment by qinggegeya** [comment]
我也是一样的问题。。。。
