### ISSUE TITLE
mac下路径问题

### ISSUE THREAD

**Issue by PeteLing** [bsmali4/xssfork#23]
mac下python3使用，报错
Traceback (most recent call last):
  File "xssforkapi.py", line 11, in <module>
    import web_service
  File "/Users/lateink/Documents/tools/xssfork/web_service.py", line 15, in <module>
    from common import log
  File "/Users/lateink/Documents/tools/xssfork/common/__init__.py", line 11, in <module>
    from taskschedule.task_schedule import CompletePacket
  File "/Users/lateink/Documents/tools/xssfork/common/../taskschedule/__init__.py", line 13, in <module>
    from common import log
  File "/Users/lateink/Documents/tools/xssfork/common/log.py", line 9, in <module>
    from path import XSS_FORK_PATH
ModuleNotFoundError: No module named 'path'
python3兼容性没做好

**Comment by PeteLing** [comment]
路径导入 很有问题

**Comment by bsmali4** [comment]
嗯，当时基本没做兼容python3。
