### ISSUE TITLE
只发送了一个请求

### ISSUE THREAD

**Issue by shadow4u** [bsmali4/xssfork#3]
使用xssfork，injected payloads数一直在空跑，实际检测服务器上，只收到一个请求，也就是说除了check url的请求之外，根本没payloads发送出去，什么原因？

**Comment by bsmali4** [comment]
请问你的是伪静态吗？如果遇到空跑很多境况都是没有指定参数，指定参数用 *

**Comment by shadow4u** [comment]
不是伪静态，就是简单的php demo适用工具。python2.7.12，做了多种尝试，换了几个版本的ubuntu还是有上述payloads空跑问题，看exceptionlog主要是两处，因为阅读代码能力比较烂，不知道改哪些地方。改用windows，替换部分代码比如os.pgkill，使用同样的命令可以成功跑起来，通过日志、截图和User-Agent，作者应该使用的是mac，难道和ubuntu环境有差异，ds买不起mac怎么办。成功跑起来后，确实是一款不错的工具，star for you。

附上ubuntu exceptionlog，老大有兴趣可以看看啥原因。
Traceback (most recent call last):
  File "/home/test/xssfork-master/common/utils.py", line 40, in start_with
    if string.strip().index(substring) == 0:
ValueError: substring not found
Traceback (most recent call last):
  File "/home/test/xssfork-master/common/../taskschedule/task_thread.py", line 176, in run
    self.check_xss(payload)
  File "/home/test/xssfork-master/common/../taskschedule/task_thread.py", line 142, in check_xss
    child_process, payload = self.sub_process_open(payload)
  File "/home/test/xssfork-master/common/../taskschedule/task_thread.py", line 122, in sub_process_open
    request_command, url_payload, destination_command = self.get_cmd(payload)
  File "/home/test/xssfork-master/common/../taskschedule/task_thread.py", line 100, in get_cmd
    url_payload = self.replace_url_to_payload(payload)
  File "/home/test/xssfork-master/common/../taskschedule/task_thread.py", line 89, in replace_url_to_payload
    url_payload = re.subn(r'bsmali4_(?:int|mix|other|str|float)', payload, url_payload)[0]
  File "/usr/lib/python2.7/re.py", line 166, in subn 
    return _compile(pattern, flags).subn(repl, string, count)
  File "/usr/lib/python2.7/re.py", line 286, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python2.7/re.py", line 266, in _compile_repl
    p = _cache_repl.get(key)
TypeError: unhashable type: 'dict'
