### ISSUE TITLE
Kali,python 2.7环境启动报错

### ISSUE THREAD

**Issue by mtgamew** [bsmali4/xssfork#8]
刚才下的新版，报错信息如下，想问一下如何解决？
Traceback (most recent call last):
  File "./xssfork.py", line 12, in <module>
    from common import log
  File "/root/Desktop/xssfork-master/common/__init__.py", line 11, in <module>
    from taskschedule.task_schedule import CompletePacket
  File "/root/Desktop/xssfork-master/common/../taskschedule/__init__.py", line 38, in <module>
    from thirdparty.requests import request
  File "/root/Desktop/xssfork-master/taskschedule/../thirdparty/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/root/Desktop/xssfork-master/taskschedule/../thirdparty/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

**Comment by bsmali4** [comment]
本身这个问题是我在开发的时候把很多库都集成进去了，kail下我试过，的确会出现这样的问题。我之前也修改好了，马上push上去。

**Comment by bsmali4** [comment]
代码改好了，你可以再试下

**Comment by mtgamew** [comment]
嗯刚才试了新版的，还是会报错，不过和之前的不太一样

Traceback (most recent call last):
  File "./xssfork.py", line 87, in <module>
    help()
  File "./xssfork.py", line 65, in help
    logger = log.get_logger()
  File "/root/Desktop/xssfork-master/common/log.py", line 27, in get_logger
    init_config()
  File "/root/Desktop/xssfork-master/common/log.py", line 55, in init_config
    stream_handler = get_stream_handler()
  File "/root/Desktop/xssfork-master/common/log.py", line 44, in get_stream_handler
    from colorlog import ColoredFormatter
ImportError: No module named colorlog

不知道是不是我环境的问题？

**Comment by mtgamew** [comment]
刚才试了一下，错误变了，不知道是不是环境的问题？
Traceback (most recent call last):
  File "./xssfork.py", line 87, in <module>
    help()
  File "./xssfork.py", line 65, in help
    logger = log.get_logger()
  File "/root/Desktop/sicklepoc-master/plugins/xssfork-master/common/log.py", line 27, in get_logger
    init_config()
  File "/root/Desktop/sicklepoc-master/plugins/xssfork-master/common/log.py", line 55, in init_config
    stream_handler = get_stream_handler()
  File "/root/Desktop/sicklepoc-master/plugins/xssfork-master/common/log.py", line 44, in get_stream_handler
    from colorlog import ColoredFormatter
ImportError: No module named colorlog
